esphome:
  name: esphome_p4_matrix_panels
  friendly_name: P4 Matrix Panel
  min_version: 2025.11.0
  name_add_mac_suffix: false

esp32:
  variant: esp32
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

external_components:
  - source: github://TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper@main
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

time:
  - platform: homeassistant
    id: ha_time

display:
  - platform: hub75_matrix_display
    id: matrix
    width: 64
    height: 32
    chain_length: 1
    brightness: 70
    R1_pin: GPIO26
    G1_pin: GPIO27
    B1_pin: GPIO14
    R2_pin: GPIO12
    G2_pin: GPIO13
    B2_pin: GPIO15
    A_pin: GPIO23
    B_pin: GPIO22
    C_pin: GPIO21
    D_pin: GPIO19
    E_pin: GPIO18
    CLK_pin: GPIO25
    LAT_pin: GPIO32
    OE_pin: GPIO33
    update_interval: 500ms
    lambda: |-
      // test: vul scherm
      it.fill(esphome::display::Color(255,0,0));